### ISSUE TITLE
pickle storage doesnt appear to work on Mac

### ISSUE THREAD

**Issue by philipbeadle** [holochain/holoscape#18]
Ive had to set the storage to memory for now as restarting with pickle doesnt appear to work.

**Comment by philipbeadle** [comment]
I get same issues with file as well.

```
Redirecting to: /Users/philipbeadle/Library/Application Support/Holoscape-default/UIs/peer-chat/index.svg
thread 'jsonrpc-eventloop-1' panicked at 'Context::block_on() waiting for future but instance is not alive anymore => we gotta let this thread panic!', core/src/context.rs:322:17
stack backtrace:

   0:        0x1058fb4b2 - std::panicking::default_hook::{{closure}}::he6e7f44710914651

{"signal":{"signal_type":"Trace","action":{"action_type":"SignalZomeFunctionCall","data":{"id":{"prefix":29,"offset":41},"zome_name":"chat","cap":{"cap_token":"QmPBfyG54fjzgKHK6qfsnR2nusTRfjNFYRnsU4J6vr4nZB","provenance":["HcScjeDFGt6ubjxftt5N4faykFeYn98v4U6e9DPJKRhia3mv9v9zj6xFJ9jXiui","EawcdQZZEAJC49ZNsUNfl9OkqSIOzwrm2zervCelv8CfumS0h1zKgroM0oESFs7deJth+xAs6iHf/nqbpAYSDA=="]},"fn_name":"get_my_member_profile","parameters":"{}"}},"id":{"prefix":29,"offset":47}},"instance_id":"peer-chat-public"}
{"signal":{"signal_type":"Trace","action":{"action_type":"SignalZomeFunctionCall","data":{"id":{"prefix":29,"offset":41},"zome_name":"chat","cap":{"cap_token":"QmPBfyG54fjzgKHK6qfsnR2nusTRfjNFYRnsU4J6vr4nZB","provenance":["HcScjeDFGt6ubjxftt5N4faykFeYn98v4U6e9DPJKRhia3mv9v9zj6xFJ9jXiui","EawcdQZZEAJC49ZNsUNfl9OkqSIOzwrm2zervCelv8CfumS0h1zKgroM0oESFs7deJth+xAs6iHf/nqbpAYSDA=="]},"fn_name":"get_my_member_profile","parameters":"{}"}},"id":{"prefix":29,"offset":47}},"instance_id":"peer-chat-public"}
   1:        0x1058fb17b - std::panicking::default_hook::h084a6ff33065f643
   2:        0x1058fbc90 - std::panicking::rust_panic_with_hook::h5b1f716b691932d4
   3:        0x1056cb2d4 - core::ptr::real_drop_in_place::h4af06ea65dbd8c29

   4:        0x10501744f - holochain_core::context::Context::block_on::h49d7e37ca823dd3c
   5:        0x104e7be25 - holochain_conductor_api::holochain::Holochain::call::hcc3f39e442d89302
   6:        0x104e5d042 - holochain_conductor_api::interface::ConductorApiBuilder::method_call::h46ef0d99f0526352
   7:        0x104e8fbe3 - <F as jsonrpc_core::calls::RpcMethodSimple>::call::heb1bc7ce653915fa
   8:        0x104d9b9e9 - <F as jsonrpc_core::calls::RpcMethod<T>>::call::hc557150532478dd9

{"signal":{"signal_type":"Consistency","event":"{\"SignalZomeFunctionCall\":[\"chat/get_my_member_profile\",{\"prefix\":29,\"offset\":41}]}","pending":[{"event":"{\"ReturnZomeFunctionResult\":[\"chat/get_my_member_profile\",{\"prefix\":29,\"offset\":41}]}","group":"Source"}]},"instance_id":"peer-chat-public"}
{"signal":{"signal_type":"Consistency","event":"{\"SignalZomeFunctionCall\":[\"chat/get_my_member_profile\",{\"prefix\":29,\"offset\":41}]}","pending":[{"event":"{\"ReturnZomeFunctionResult\":[\"chat/get_my_member_profile\",{\"prefix\":29,\"offset\":41}]}","group":"Source"}]},"instance_id":"peer-chat-public"}
   9:        0x1051e30cf - futures::future::lazy::Lazy<F,R>::get::hb39ae81f582347e3
  10:        0x1051e320e - <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll::h7267501a982b5cad
  11:        0x1051e91ab - futures::future::chain::Chain<A,B,C>::poll::h631fe2f5e9cda174
  12:        0x1051e7544 - <futures::future::then::Then<A,B,F> as futures::future::Future>::poll::heada79c9ad674c66

  13:        0x1051e27d4 - <futures::future::either::Either<A,B> as futures::future::Future>::poll::h06e47f4999e20fd5

  14:        0x1051e285a - <futures::future::either::Either<A,B> as futures::future::Future>::poll::h8cbb7deeab95ed9c

  15:        0x1051e740b - <futures::future::map::Map<A,F> as futures::future::Future>::poll::hdab08a28ed1937f3

  16:        0x1051e2835 - <futures::future::either::Either<A,B> as futures::future::Future>::poll::h2dd01206f606f966
  17:    
    0x1051e27f9 - <futures::future::either::Either<A,B> as futures::future::Future>::poll::h0e8aa2d668eb6aa1
  18:        0x1051e288f - <futures::future::either::Either<A,B> as futures::future::Future>::poll::he29c9de55c6b0e9c
  19:        0x1051e718a - <futures::future::map::Map<A,F> as futures::future::Future>::poll::ha5bc85a9addbf7da

  20:        0x104dc0de8 - <futures::future::map::Map<A,F> as futures::future::Future>::poll::h4aa0cd881c10eaf1
  21
:        0x104db2e66 - <futures::future::select::Select<A,B> as futures::future::Future>::poll::h0a1c7ec8d27cf4a4
  22:        0x104dc0c6c - <futures::future::map::Map<A,F> as futures::future::Future>::poll::h3cce067e7e6b2463

  23:        0x104e6c430 - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h3357692f06a9ca6b

  24:        0x10567fb29 - futures::task_impl::std::set::hb3e69d665e3fd8e7

  25:        0x10567fa15 - futures::task_impl::Spawn<T>::enter::he7b48c01684d188d

  26:        0x10567f931 - futures::task_impl::Spawn<T>::poll_fn_notify::h4dde5f1683de6974

  27:        0x10567ce56 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hfc4e11e7585c21c7

  28:        0x105678fd2 - std::panicking::try::do_call::h091278933a10d21c

  29:        0x105905f2f - __rust_maybe_catch_panic

  30:        0x105678f73 - std::panicking::try::h27c2591509d91ca0

  31:        0x10567cec0 - std::panic::catch_unwind::h8157e92f81b8bef5

  32:        0x10567e117 - tokio_threadpool::task::Task::run::h01ffe71d0e7e5a3e
  33:        0x10567a2ef - tokio_threadpool::worker::Worker::run_task::hea362de0a6a1a206

  34:        0x105679b64 - tokio_threadpool::worker::Worker::run::hc1469067df8901fb

  35:        0x105662cb6 - std::thread::local::LocalKey<T>::try_with::h0ae4bf77e31cfb4a

  36:        0x105662b67 - std::thread::local::LocalKey<T>::with::h013c16063f6b722c

  37:        0x105663a99 - tokio_timer::timer::handle::with_default::h4121ab5af4962e19

  38:        0x105662e0c - std::thread::local::LocalKey<T>::try_with::h43694632a01fbc7a

  39:        0x105662b97 - std::thread::local::LocalKey<T>::with::h09028c1c38a69163

  40:        0x105666110 - tokio_timer::clock::clock::with_default::hc48524c58fe53a06

  41:        0x105662fea - std::thread::local::LocalKey<T>::try_with::hc3587e06b60bc001

  42:        0x105662be7 - std::thread::local::LocalKey<T>::with::h0e0620bc2e6732d6

  43:        0x105663f5a - tokio_reactor::with_default::h47ee12800ac41341

  44:        0x105668aa4 - tokio::runtime::threadpool::builder::Builder::build::{
{closure}}::h8b546848c02eb66e

  45:        0x10567ea5d - std::thread::local::LocalKey<T>::try_with::h1e9c6b1323c4252b

  46:        0x10567e95a - 
std::thread::local::LocalKey<T>::with::h54f03a14336520f1

  47:        0x10567d70d - tokio_executor::global::with_default::h24cdd20079949d7c

  48:        0x10567eb6d - std::thread::local::LocalKey<T>::try_with::h3a9a4302d1183ce3

  49:        0x10567e9a7 - std::thread::local::LocalKey<T>::with::hac6175b1725b5ba1

  50:        0x10567998d - tokio_threadpool::worker::Worker::do_run::h15f7b290d2f54bf0

  51:        0x105677a21 - std::sys_common::backtrace::__rust_begin_short_backtrace::h271753075e870944

  52:        0x10567ce1f - <std::panic::AssertUnwindSafe<F> as core::ops::function::
FnOnce<()>>::call_once::hd2f4eeaf338db4c5

  53:        0x10567900d - std::panicking::try::do_call::h22015b9e87cb38c5
  54:        0x105905f2f - __rust_maybe_catch_panic
  55:        0x105678f10 - std::panicking::try::
h1df7c1adbb407855

  56:        0x10567cefc - std::panic::catch_unwind::he08d17edd285c6ee

  57:        0x10567d213 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h3242cdebd285d32b

  58:        0x1058e982e - <alloc::boxed::Box<F> as 
core::ops::function::FnOnce<A>>::call_once::haa2c7551911d4476
  59:      
  0x10590546e - std::sys::unix::thread::Thread::new::thread_start::hb153111b0762b747
  60:     0x7fff7ac862eb - _pthread_body
  61:     0x7fff7ac89249 - _pthread_start


```

**Comment by philipbeadle** [comment]
I can see the txt files created in the folder for both cas and eav.

**Comment by Connoropolous** [comment]
Oh, I've been seeing that issue too! It happens only when you use pickle storage??

**Comment by Connoropolous** [comment]
Oh, no, I see that happens both with 'file' and with 'pickle' you said

**Comment by philipbeadle** [comment]
happens with all storage.

**Comment by thedavidmeister** [comment]
i could replicate only when i fully rebooted my machine (simply killing the conductor and restarting it was ok)

note that lmdb is the default in latest holoscape, so here's a dump i have

```
DEBUG 2019-10-28 16:47:06 [holochain_conductor_lib::conductor::base] main crates/conductor_lib/src/conductor/base.rs:267 starting signal loop
DEBUG 2019-10-28 16:47:06 [holochain::Personas & Profiles] main crates/core/src/workflows/application.rs:25 dna/initialize: No DNA and agent in chain so assuming uninitialized: ErrorGeneric("Network::start() called without DNA")

thread 'main' panicked at 'Context::block_on() waiting for future but instance is not alive anymore => we gotta let this thread panic!', crates/core/src/context.rs:315:17
stack backtrace:

   0:     0x55cbca6226f8 - std::panicking::default_hook::{{closure}}::h7c4f6f6170cc3cf6
   1:     0x55cbca621e58 - std::panicking::rust_panic_with_hook::h7fedb25d8f7a616a
   2:     0x55cbc9d02004 - std::panicking::begin_panic::hee30c2931708c00b
   3:     0x55cbc9d6a588 - holochain_core::instance
::Instance::initialize::h2bc866620d3526be
   4:     0x55cbc9b2ea84 - holochain_conductor_lib::conductor::base::Conductor::instantiate_from_config::{{closure}}::hdadf2335075dc96c
   5:     0x55cbc9b24817 - holochain_conductor_lib::conductor::base::Conductor::instantiate_from_config::hba3d77064a67e170
   6:     0x55cbc9b4e1cd - holochain_conductor_lib::conductor::base::Conductor::boot_from_config::h4473648fa081865f
   7:     0x55cbca68a5e9 - holochain::main::ha8307f3299ca87e9
   8:     0x55cbca6947b3 - std::rt::lang_start::{{closure}}::h83b70ac87ab49379
   9:     0x55cbca68601e - main
  10:     0x7f96cf4adb8e - __libc_start_main
  11:     0x55cbc98392aa - _start
  12:                0x0 - <unknown>

thread 'handle_authoring_list/puid-6-3' panicked at 'Tried to use dropped state', src/libcore/option.rs:1065:5
stack backtrace:
   0:     0x55cbca6226f8 - std::panicking::default_hook::{{closure}}::h7c4f6f6170cc3cf6
   1:     0x55cbca621e58 - std::panicking::rust_panic_with_hook::h7fedb25d8f7a616a
   2:     0x55cbca62197f - std::panicking::continue_panic_fmt::hed2a79ffb3c5014c
   3:     0x55cbca63b176 - rust_begin_unwind

   4:     0x55cbca64679c - core::panicking::panic_fmt::hcd868b6ef07f5b76
   5:     0x55cbca649846 - core::option::expect_failed::hfebe20ebb62098ad
   6:     0x55cbc9d53b37 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc921d958b15536c1
   7:     0x55cbc9ddcb7f - core::ops::function::FnOnce::call_once{{vtable.shim}}::h87538bc82babefcb
   8:     0x55cbca63ad1f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h56322f6b657cd33d
   9:     0x55cbca63c77c - std::sys::unix::thread::Thread::new::thread_start::h588aedefb535eac7
  10:     0x7f96cf85eef7 - start_thread
  11:     0x7f96cf57e22f - __GI___clone
  12:                0x0 - <unknown>

thread 'handle_gossip_list/puid-6-4' panicked at 'Tried to use dropped state', src/libcore/option.rs:1065:5
stack backtrace:
   0:     0x55cbca6226f8 - std::panicking::default_hook::{{closure}}::h7c4f6f6170cc3cf6
   1:     0x55cbca621e58 - std::panicking::rust_panic_with_hook::h7fedb25d8f7a616a
   2:     0x55cbca62197f - std::panicking
::continue_panic_fmt::hed2a79ffb3c5014c
   3:     0x55cbca63b176 - rust_begin_unwind
   4:     0x55cbca64679c - core::panicking::panic_fmt::hcd868b6ef07f5b76
   5:     0x55cbca649846 - core::option::expect_failed::hfebe20ebb62098ad
   6:     0x55cbc9d3b1c6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2d09dd3a50ed7f68
   7:     0x55cbc9ddb29f - core::ops::function::FnOnce::call_once{{vtable.shim}}::ha0cd4d805142746c
   8:     0x55cbca63ad1f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h56322f6b657cd33d
   9:     0x55cbca63c77c - std::sys::unix::thread::Thread::new::thread_start::h588aedefb535eac7
  10:     0x7f96cf85eef7 - start_thread
  11:     0x7f96cf57e22f - __GI___clone
  12:                0x0 - <unknown>

holochain process terminated with exit code 101

```

**Comment by lucksus** [comment]
There is a fix for this here: https://github.com/holochain/holochain-rust/pull/1808

**Comment by philipbeadle** [comment]
Sorted :)
